[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
two_phase_commit = "2PCPgunAXWWUSiKGChz6UQuspAz6Tgqc7mNdWkanGSMM"
demo_participant = "7tQZaZaLooXGEXgpDfDakxMS69j4t8KsrqeGZYeLLbCn"

[programs.devnet]
two_phase_commit = "2PCPgunAXWWUSiKGChz6UQuspAz6Tgqc7mNdWkanGSMM"
demo_participant = "7tQZaZaLooXGEXgpDfDakxMS69j4t8KsrqeGZYeLLbCn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
